Fix #39
bbopt/NOMAD.jl pull request #59
Opened 2022-07-17 02:27 UTC by SobhanMP

This makes it possible to run threaded function in nomad.jl

ref: https://discourse.julialang.org/t/x/84343

2022-07-17 02:33 UTC, SobhanMP commented
PS. i removed the finalizer because it's non deterministic when it is ran. it's pointless in the code right now.

2022-07-17 02:53 UTC, SobhanMP commented
ah yes, windows does not have sigaction

2022-07-17 07:30 UTC, mkitti commented on src/c_wrappers.jl
> +                       exists_inf_sol, x_inf_sol, outputs_inf_sol, pointer_from_objref(prob))
No, leave this as it was. Otherwise, you will have to use `GC.@preserve`.

2022-07-17 16:32 UTC, mkitti requested changes
Thr ccall still needs to be fixed.

2022-07-17 16:32 UTC, mkitti commented on src/c_wrappers.jl
> +                       exists_inf_sol, x_inf_sol, outputs_inf_sol, pointer_from_objref(prob))
Remove the `pointer_from_objref`.

2022-07-17 16:48 UTC, mkitti requested changes
I think we want to do a `try` ... `finally` here with the free occurring in the finally. The try should start just after we obtain the CNomadProblem.

In case of an error, we should always free.

2022-07-17 16:59 UTC, SobhanMP commented
yeah, i'll fix this tonight

2022-07-19 21:06 UTC, SobhanMP commented
@amontoison this is ready to be merged, it's either this or a fork of nomad that doesn't set handlers. After than i'll have another patch ready for the compatibility with nomad 4.2

2022-07-20 12:56 UTC, merged

2023-08-16 20:00 UTC, martinmestre commented
> This makes it possible to run threaded function in nomad.jl
> 
> ref: https://discourse.julialang.org/t/x/84343

Hi, how should I run multithread with NOMAD.jl. I tried with the following:
```
function bb(x)
        χ² = χ²Full(x, p)
        c = -1.0
        success = true
        count_eval = true
        bb_outputs = [χ²;c]
        return (success, count_eval, bb_outputs)
    end
```
but it gives the following error:
```
Threads=6
m = 300.0
sol_file = "param_optim_pot_m300.txt"
r☼ = 8.122
maxiters = 500
i=3 1
i=1 2
i=8 6
i=6 5
i=7 4
i=5 3
lb -- ub = , [35.0, 28.0, 1.0e-5] -- [40.0, 31.0, 0.002505]
lb -- ub = , [40.0, 25.0, 1.0e-5] -- [45.0, 28.0, 0.002505]
lb -- ub = , [40.0, 28.0, 0.002505] -- [45.0, 31.0, 0.005]
Warning: SubproblemManager::clear() called on non-empty SubproblemManager
lb -- ub = , [40.0, 28.0, 1.0e-5] -- [45.0, 31.0, 0.002505]
lb -- ub = , [40.0, 25.0, 0.002505] -- [45.0, 28.0, 0.005]
lb -- ub = , [35.0, 25.0, 1.0e-5] -- [40.0, 28.0, 0.002505]
free(): double free detected in tcache 2

[85675] signal (6.-6): Aborted
in expression starting at /mnt/md1/mmestre/work/2020/halostream/sources/stream_fit/pipeline_paper/optim_pot.jl:140
Caught seg fault in thread 0Caught seg fault in thread 0

terminate called after throwing an instance of 'NOMAD_4_3::Exception'
terminate called recursively
Aborted
```
What could be the problem?
Thanks a lot.